<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>



<div class="page-header">
    <h1>
        Add User
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "userslist/listingpage",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Firstname", "size" => 20, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Lastname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Lastname", "size" => 20, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGender" class="col-sm-2 control-label">Gender</label>
    <div class="col-sm-2">
       
       <?php echo $this->tag->radioField(["Gender","value"=> "M", "checked"=>"checked"])  ?>
        <label for="fielMaleGender" class=" control-label">Male</label>
    </div>
    <div class="col-sm-2">
       
       <?php echo $this->tag->radioField(["Gender","value"=> "F"])  ?>
       <label for="fieldFemaleGender" class=" control-label">Female</label>
    </div>
</div>

<div class="form-group">
    <label for="fieldEducation" class="col-sm-2 control-label">Education</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["Education", ["BBA" => "BBA","B.E." => "B.E.","BSc." => "BSc.","B.Tech" => "B.Tech","M.E." => "M.E.","MBA" => "MBA"], "class" => "form-control", "id" => "fieldEducation"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSkills" class="col-sm-2 control-label">Skills</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Skills", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSkills"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
