<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            
            <li class="next"><?php echo $this->tag->linkTo(["userslist/new", "Adduser"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>List Users</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Education</th>
                <th>Skills</th>

            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $userslist): ?>
            <tr>
                <td><?php echo $userslist->getFirstname() ?></td>
                <td><?php echo $userslist->getLastname() ?></td>
                <td><?php echo $userslist->getEmail() ?></td>
                <td><?php echo $userslist->getGender() ?></td>
                <td><?php echo $userslist->getEducation() ?></td>
                <td><?php echo $userslist->getSkills() ?></td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("userslist/retrieve", "First") ?></li>
                <li><?php echo $this->tag->linkTo("userslist/retrieve?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("userslist/retrieve?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("userslist/retrieve?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
